

spring:
  application:
    name: s1rates
  profiles:
    active:
      - default
  cloud:
    config:
      uri:
        - http://localhost:8888
  devtools:
    restart:
      enabled: true
      additional-paths:
        - templates/**
      additional-exclude: static/**,public/**